group :test do
  gem 'capybara', '>= 2.15'
  # https://github.com/titusfortner/webdrivers
  gem 'selenium-webdriver'
  gem 'webdrivers', '~> 4.0'
  gem 'sys-uname', '~> 1.2', '>= 1.2.1'

  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard-minitest',     '2.3.1'
end